services:
  - type: web
    name: campaign-management-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: campaign-db
          property: connectionString
      - key: DASHBOARD_PASSWORD
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

databases:
  - name: campaign-db
    databaseName: campaign_db
    user: campaign_user